# Generated by Django 3.0.2 on 2020-01-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='common_words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('freq', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
