# Generated by Django 3.0.2 on 2020-01-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='common_words',
            new_name='common_word',
        ),
    ]
