# Generated by Django 3.0.2 on 2020-01-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200128_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common_word',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
